language: ruby
cache: bundler
sudo: false
matrix:
  include:
    - rvm: 2.4.6
      os: linux
    - rvm: 2.5.5
      os: linux
    - rvm: 2.6.3
      os: linux
before_install:
  - gem update --system=2.7.8
